# Generated by Django 3.2.8 on 2022-05-18 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pims',
            fields=[
                ('pims_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('session_hash', models.CharField(max_length=40, unique=True)),
                ('stage', models.CharField(default='1', max_length=10, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name='Father Name')),
                ('mother_name', models.CharField(blank=True, max_length=50, verbose_name='Mother Name')),
                ('aadhar_no', models.PositiveBigIntegerField(blank=True, unique=True)),
                ('dob', models.DateField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('religion', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('mother_tongue', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=50)),
                ('institute', models.CharField(blank=True, max_length=100)),
                ('discipline', models.CharField(blank=True, max_length=100)),
                ('passing_grade', models.CharField(blank=True, max_length=10)),
                ('passing_percentage', models.FloatField(blank=True, null=True)),
                ('passing_year', models.DateField(blank=True, null=True)),
                ('degree_type', models.CharField(blank=True, max_length=20)),
                ('course_coordinator', models.CharField(blank=True, max_length=50)),
                ('organisation', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(blank=True, max_length=100)),
                ('org_address', models.CharField(blank=True, max_length=100)),
                ('org_city', models.CharField(blank=True, max_length=50)),
                ('org_country', models.CharField(blank=True, max_length=50)),
                ('org_state', models.CharField(blank=True, max_length=50)),
                ('org_district', models.CharField(blank=True, max_length=50)),
                ('course_start_date', models.DateField(blank=True, null=True)),
                ('course_end_date', models.DateField(blank=True, null=True)),
                ('is_course_completed', models.BooleanField(blank=True, default=True, null=True)),
                ('course_grade', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('post_office', models.CharField(blank=True, max_length=50)),
                ('pincode', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('curr_address', models.CharField(blank=True, max_length=200)),
                ('curr_city', models.CharField(blank=True, max_length=50)),
                ('curr_district', models.CharField(blank=True, max_length=50)),
                ('curr_state', models.CharField(blank=True, max_length=50)),
                ('curr_post_office', models.CharField(blank=True, max_length=50)),
                ('curr_pincode', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('director_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
