# Generated by Django 3.2.8 on 2022-05-18 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=50, verbose_name='File Name')),
                ('file_description', models.CharField(blank=True, max_length=200, verbose_name='File Description')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_open', models.BooleanField(blank=True, default=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file_access', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_by+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('is_opened', models.BooleanField(default=False, null=True)),
                ('sent_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('file_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='efile.file')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('doc_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('doc_name', models.CharField(blank=True, max_length=50, verbose_name='File Name')),
                ('doc_description', models.CharField(blank=True, max_length=200, verbose_name='File Description')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='efile.file')),
                ('uploaded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('is_opened', models.BooleanField(default=False, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('doc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='efile.docs')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
