# Generated by Django 3.2.8 on 2022-05-18 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('reason', models.CharField(max_length=300)),
                ('is_forwarded', models.BooleanField(blank=True, null=True)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('applied_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('forwarded_date', models.DateTimeField(null=True)),
                ('approved_date', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
